"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# ====================
# CORE CONFIGURATION
# ====================

DEBUG = os.getenv("DJANGO_ENABLE_DEBUG", default="False").lower() == "true"
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_URLCONF = 'server.urls'
WSGI_APPLICATION = 'server.wsgi.application'
SITE_ID = 1  # For flatpages
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
DATABASES = {'default': dj_database_url.config(conn_max_age=600)}



# ====================
# SECURITY SETTINGS
# ====================

ENFORCE_SSL = os.getenv("ENFORCE_SSL", str(not DEBUG)).lower() == "true"

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = ENFORCE_SSL
X_FRAME_OPTIONS = "SAMEORIGIN"
INTERNAL_IPS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = ['*']

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

CSRF_TRUSTED_ORIGINS = []
if os.environ.get('DOMAIN'):
    CSRF_TRUSTED_ORIGINS.append(f'https://{os.environ["DOMAIN"]}')

# ====================
# CACHING
# ====================

REDIS_ENABLED = os.getenv("USE_REDIS_CACHE", str(not DEBUG)).lower() == "true"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    } if REDIS_ENABLED else {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
    }
}

# ====================
# AUTHENTICATION
# ====================

AUTH_USER_MODEL = 'puzzlehunt.User'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'account_login'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Configuration
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' if ENFORCE_SSL else 'http'
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
ACCOUNT_SIGNUP_FORM_CLASS = 'puzzlehunt.auth_forms.MyCustomSignupForm'
ACCOUNT_USER_DISPLAY = lambda user: user.display_string()
ACCOUNT_FORMS = {
    'login': 'puzzlehunt.auth_forms.ModifiedLoginForm',
}

# ====================
# FILE HANDLING
# ====================

STATIC_ROOT = '/app/static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = ["/app/custom_static",]
MEDIA_ROOT = "/app/media/"
MEDIA_URL = '/media/'
PROTECTED_URL = '/protected/'

# Sendfile Configuration
SENDFILE_BACKEND = "django_sendfile.backends.nginx"
SENDFILE_ROOT = MEDIA_ROOT

# ====================
# APPLICATION DEFINITION
# ====================

INSTALLED_APPS = [
    # Dependencies for admin interface
    'colorfield',
    'admin_interface',
    
    # Django built-in (in recommended order)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.flatpages',
    
    # Core app
    'constance',
    'puzzlehunt',
    
    # All auth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.apple',
    'allauth.socialaccount.providers.discord',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.microsoft',
    'allauth.socialaccount.providers.twitter',
    
    # Other third-party apps (order not critical)
    'django_sendfile',
    'django_htmx',
    'impersonate',
    'huey.contrib.djhuey',
    'django_eventstream',
    'crispy_forms',
    'crispy_bulma',
    'mathfilters',
    'anymail',
]

# ====================
# MIDDLEWARE
# ====================

MIDDLEWARE = [
    'django_grip.GripMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    'impersonate.middleware.ImpersonateMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

# ====================
# TEMPLATE CONFIGURATION
# ====================

develop_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]
production_loaders = [
    # TODO: We many want to write a custom loader that allows invalidation of template caches
    ("django.template.loaders.cached.Loader", [
        "django.template.loaders.filesystem.Loader",
        "django.template.loaders.app_directories.Loader",
    ])
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            '/app/custom_templates/',  # Custom templates take precedence
            '/app/media/trusted/',
        ],
        'OPTIONS': {
            'builtins': ['puzzlehunt.templatetags.hunt_tags'],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
            'loaders': develop_loaders if DEBUG else production_loaders,
        },
    },
]

# ====================
# THIRD-PARTY SETTINGS
# ====================

# Constance (Dynamic Settings)
CONSTANCE_CONFIG = {
    # Site Settings
    'SITE_TITLE': ('PuzzleSpring', 'The title of the site'),
    
    # Team Settings
    'NO_TEAMS_MODE': (False, 'If enabled, each user will be their own team'),
    'TEAM_MEMBERS_CAN_SEE_NAMES': (True, 'If enabled, team members will be able to see users names on the team page'),
    
    # Hunt Display Settings
    'SINGLE_HUNT_MODE': (False, 'If enabled, only one hunt will be visible and accessible'),
    'HUNTS_HAVE_LOCATION': (True, 'If enabled, hunts will display their location on the main page'),
    'SHOW_ARCHIVE_SEASONS': (True, 'If enabled, the archive page will show season labels on old hunts'),
    
    # Puzzle Display Settings
    'PROGRESS_FULL_PUZZLE_NAMES': (False, 'If enabled, the progress page will show full puzzle names'),
    'SHOW_SOLVE_COUNT_ON_PUZZLE': (True, 'If enabled, the puzzle page the current number of solves'),
    'SHOW_UPDATE_FOR_LOCKED_PUZZLES': (True, 'If enabled, updates will be shown even when the puzzle is locked'),
    
    # Registration Settings
    'HUNT_REGISTRATION_LOCKOUT': (2, 'The number of days before the hunt when registration locks'),
    
    # Communication Settings
    'CONTACT_EMAIL': ('test@test.com', 'The contact email for help links'),
    
    # Submission and Hint Settings
    'SHOW_SUBMISSION_USER': (True, 'If enabled, the submissions page will display usernames'),
    'SHOW_HINT_USER_STAFF': (True, 'If enabled, the staff hints page will show the staff responder'),

    # Image settings
    'NAVBAR_IMAGE': ('', 'Image displayed on the navbar', 'image_field'),
    'EMBED_IMAGE': ('', 'Image displayed in embeds', 'image_field'),
}

CONSTANCE_ADDITIONAL_FIELDS = {
    bool: ['django.forms.fields.BooleanField', {
        'widget': 'puzzlehunt.widgets.ToggleSwitchWidget',
        'required': False,
    }],
    'image_field': ['django.forms.ImageField', {
        'widget': 'puzzlehunt.widgets.ImageWidget',
    }]
}
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
CONSTANCE_FILE_ROOT = 'constance'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = ("bulma",)
CRISPY_TEMPLATE_PACK = "bulma"
CRISPY_FAIL_SILENTLY = not DEBUG

# Impersonation
IMPERSONATE = {
    'REQUIRE_SUPERUSER': True
}

# Eventstream
GRIP_URL = 'http://pushpin:5561'
EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'
EVENTSTREAM_CHANNELMANAGER_CLASS = 'puzzlehunt.utils.PuzzlehuntChannelManager'

# Huey (Task Queue)
HUEY = {
    'huey_class': 'huey.RedisHuey',
    'immediate': False,
    'connection': {
        'host': 'redis',
    }
}

# ====================
# INTERNATIONALIZATION
# ====================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/New_York'  #TODO: make an env variable option
USE_I18N = True
USE_TZ = True

# ====================
# LOGGING
# ====================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'puzzlehunt': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        },
    },
}

# ====================
# EMAIL
# ====================

EMAIL_CONFIGURED = False
EMAIL_USE_TLS = True
ANYMAIL = {
    'SEND_DEFAULTS': {
        'track_clicks': False,
        'track_opens': False,
    }
}

# ====================
# DEBUG SETTINGS
# ====================

if os.environ.get("ENABLE_DEBUG_TOOLBAR"):
    DEBUG_TOOLBAR_PANELS = (
        'debug_toolbar.panels.version.VersionDebugPanel',
        'debug_toolbar.panels.timer.TimerDebugPanel',
        'debug_toolbar.panels.profiling.ProfilingDebugPanel',
    )
    INSTALLED_APPS = INSTALLED_APPS + ('debug_toolbar',)
    MIDDLEWARE = ('debug_toolbar.middleware.DebugToolbarMiddleware',) + MIDDLEWARE

# ====================
# SENTRY
# ====================

if os.environ.get("SENTRY_DSN"):
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        integrations=[DjangoIntegration()],
        send_default_pii=True
    )
