# Generated by Django 4.2 on 2024-08-22 03:49

from django.db import migrations

def add_all_permissions(apps=None, schema_editor=None):
    from django.contrib.auth.management import create_permissions

    if apps is None:
        from django.apps import apps

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=1)
        app_config.models_module = None


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0002_alter_user_display_name'),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(add_all_permissions, reverse_code=migrations.RunPython.noop),
    ]
