# Generated by Django 4.2 on 2024-08-27 23:34

from django.db import migrations, models
import puzzlehunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0004_add_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintunlockplan',
            name='num_hints',
            field=models.IntegerField(default=1, help_text='Number of hints that should be unlocked per trigger'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='location',
            field=models.CharField(blank=True, help_text='Starting location of the puzzlehunt', max_length=100),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='template_file',
            field=models.FileField(blank=True, null=True, storage=puzzlehunt.models.OverwriteStorage(), upload_to=puzzlehunt.models.get_hunt_template_path),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.CharField(help_text='A 3-8 character hex string that uniquely identifies the puzzle', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
