# Generated by Django 5.1.5 on 2025-01-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0005_development-changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='from_puzzle_pool',
            field=models.BooleanField(default=False, help_text='Whether this hint was drawn from the puzzle-specific pool'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='hint_usage_policy',
            field=models.CharField(choices=[('CANNED_FIRST', 'Canned hints must be used before regular hints'), ('EXCLUSIVE', 'Puzzles with canned hints cannot use regular hints'), ('SEPARATE_POOLS', 'Puzzle-specific hints for canned, global hints for regular')], default='SEPARATE_POOLS', help_text='How hints are allocated between canned and regular hints', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzlestatus',
            name='num_available_hints',
            field=models.IntegerField(default=0, help_text='Number of puzzle-specific hints available'),
        ),
        migrations.AddField(
            model_name='puzzlestatus',
            name='num_canned_hints_used',
            field=models.IntegerField(default=0, help_text='Number of canned hints that have been revealed to this team'),
        ),
        migrations.AddField(
            model_name='puzzlestatus',
            name='num_total_hints_earned',
            field=models.IntegerField(default=0, help_text='The total number of puzzle-specific hints this puzzle/team pair has earned'),
        ),
        migrations.CreateModel(
            name='CannedHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text of the hint', max_length=1000)),
                ('order', models.IntegerField(default=0, help_text='Order in which this hint should be shown (lower numbers first)')),
                ('puzzle', models.ForeignKey(help_text='The puzzle this canned hint belongs to', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.puzzle')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('puzzle', 'order')},
            },
        ),
        migrations.AddField(
            model_name='hint',
            name='canned_hint',
            field=models.ForeignKey(blank=True, help_text='If this was a canned hint, which one', null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzlehunt.cannedhint'),
        ),
    ]
