# Generated by Django 4.2 on 2024-08-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0006_remove_team_points_alter_puzzle_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='related_data',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='The team name as it will be shown to hunt participants', max_length=100, verbose_name='Team Name'),
        ),
    ]
