# Generated by Django 5.1.5 on 2025-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0006_hint_from_puzzle_pool_hunt_hint_usage_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='hint_usage_policy',
        ),
        migrations.AddField(
            model_name='hunt',
            name='canned_hint_policy',
            field=models.CharField(choices=[('FIRST', 'Canned hints must be used before custom hints'), ('ONLY', 'Only canned hints allowed (no custom hints)'), ('MIXED', 'Canned and custom hints can be used in any order')], default='FIRST', help_text='How canned hints interact with custom hints', max_length=5),
        ),
        migrations.AddField(
            model_name='hunt',
            name='hint_pool_allocation',
            field=models.CharField(choices=[('PUZZ', 'Use puzzle-specific hints before global hints'), ('SPLIT', 'Canned hints use puzzle pool, custom hints use global pool')], default='PUZZ', help_text='How hints are allocated between puzzle and global pools when both exist', max_length=5),
        ),
        migrations.AddField(
            model_name='hunt',
            name='hint_pool_type',
            field=models.CharField(choices=[('GLOBAL', 'Global hint pool only'), ('PUZZLE', 'Puzzle-specific hints only'), ('BOTH', 'Both global and puzzle-specific hints')], default='GLOBAL', help_text='Which hint pools are available in this hunt', max_length=6),
        ),
    ]
