# Generated by Django 4.2 on 2024-08-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0007_event_related_object_id_alter_event_related_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayOnlyHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the hunt as the public will see it', max_length=200)),
                ('start_date', models.DateTimeField(help_text='The date/time at which a hunt will become visible to registered users')),
                ('end_date', models.DateTimeField(help_text='The date/time at which a hunt will be archived and available to the public')),
                ('num_teams', models.IntegerField(help_text='The number of teams that were registered for this hunt')),
                ('num_puzzles', models.IntegerField(help_text='The number of puzzles this hunt had')),
            ],
        ),
    ]
