# Generated by Django 4.2.17 on 2025-01-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0007_remove_hunt_hint_usage_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlestatus',
            name='num_canned_hints_used',
        ),
    ]
