# Generated by Django 4.2.19 on 2025-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0008_remove_puzzlestatus_num_canned_hints_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_local',
        ),
        migrations.AddField(
            model_name='team',
            name='custom_data',
            field=models.CharField(blank=True, help_text='A field for custom registration data', max_length=100),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='canned_hint_policy',
            field=models.CharField(choices=[('ONLY', 'Only canned hints allowed (no custom hints)'), ('FIRST', 'Canned hints must be used before custom hints'), ('MIXED', 'Canned and custom hints can be used in any order')], default='FIRST', help_text='How canned hints interact with custom hints', max_length=5),
        ),
        migrations.AlterField(
            model_name='prepuzzle',
            name='name',
            field=models.CharField(help_text='The name of the puzzle as it will be seen by hunt participants', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='response_text',
            field=models.CharField(blank=True, help_text='Response to the given answer.', max_length=400),
        ),
    ]
