# Generated by Django 4.2 on 2024-08-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0008_displayonlyhunt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayonlyhunt',
            old_name='end_date',
            new_name='display_end_date',
        ),
        migrations.RenameField(
            model_name='displayonlyhunt',
            old_name='start_date',
            new_name='display_start_date',
        ),
    ]
