# Generated by Django 4.2 on 2024-08-31 12:54

from django.db import migrations, models
import puzzlehunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0009_rename_end_date_displayonlyhunt_display_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='info_page_file',
            field=models.FileField(blank=True, null=True, storage=puzzlehunt.models.OverwriteStorage(), upload_to=puzzlehunt.models.get_hunt_info_page_path),
        ),
    ]
