# Generated by Django 4.2.20 on 2025-04-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0009_remove_team_is_local_team_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='ratelimit_override',
            field=models.CharField(blank=True, default='', help_text='Override default answer submission rate limit (format: X/YZ, e.g. 3/5m)', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='ratelimit_override',
            field=models.CharField(blank=True, default='', help_text="Override hunt's rate limit (format: X/YZ, e.g. 3/5m)", max_length=20),
        ),
    ]
