# Generated by Django 4.2 on 2024-09-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0010_hunt_info_page_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepuzzle',
            name='template',
        ),
    ]
