# Generated by Django 4.2.20 on 2025-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0011_alter_hunt_ratelimit_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='badges',
            field=models.JSONField(default=list, help_text='List of badge texts earned by this team'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('puzzle', 'regex')},
        ),
    ]
