# Generated by Django 4.2 on 2024-09-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0011_remove_prepuzzle_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepuzzle',
            name='response_string',
            field=models.TextField(blank=True, default='', help_text='Data returned to the webpage for use upon solving.'),
        ),
    ]
