# Generated by Django 4.2 on 2024-09-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0012_alter_prepuzzle_response_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PSUB', 'Submission'), ('PSOL', 'Solve'), ('PUNL', 'Unlock'), ('HREQ', 'Hint Request'), ('HRES', 'Hint Response'), ('FINH', 'Finish Hunt'), ('TMJH', 'Team Join'), ('UJTM', 'User Joined Team'), ('ULTM', 'User Left Team'), ('ERRT', 'New Errata')], help_text='The type of event', max_length=4),
        ),
    ]
