# Generated by Django 4.2.20 on 2026-01-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0012_team_badges_alter_response_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('hunt', 'order_number')},
        ),
    ]
