# Generated by Django 4.2 on 2024-09-13 19:46

from django.db import migrations, models
import puzzlehunt.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0013_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntfile',
            name='file',
            field=models.FileField(storage=puzzlehunt.models.OverwriteStorage(), unique=True, upload_to=puzzlehunt.models.get_media_file_path),
        ),
        migrations.AlterField(
            model_name='prepuzzlefile',
            name='file',
            field=models.FileField(storage=puzzlehunt.models.OverwriteStorage(), unique=True, upload_to=puzzlehunt.models.get_media_file_path),
        ),
        migrations.AlterField(
            model_name='puzzlefile',
            name='file',
            field=models.FileField(storage=puzzlehunt.models.OverwriteStorage(), unique=True, upload_to=puzzlehunt.models.get_media_file_path),
        ),
        migrations.AlterField(
            model_name='solutionfile',
            name='file',
            field=models.FileField(storage=puzzlehunt.models.OverwriteStorage(), unique=True, upload_to=puzzlehunt.models.get_media_file_path),
        ),
        migrations.AlterField(
            model_name='teamrankingrule',
            name='rule_type',
            field=models.CharField(choices=[('UNLK', 'Number of Puzzles Unlocked'), ('PUZZ', 'Number of Puzzles Solved'), ('META', 'Number of Metas Solved'), ('FINL', 'Final Puzzle Solve Time'), ('LMTM', 'Last Meta Solve Time'), ('LAST', 'Last Solve Time'), ('PNTS', 'Number of Points'), ('HINT', 'Number of Hints Left')], help_text='The type of ranking rule', max_length=4),
        ),
    ]
