# Generated by Django 4.2.20 on 2026-01-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0013_puzzle_order_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='matched_response',
            field=models.ForeignKey(
                blank=True,
                help_text='The custom Response that matched this submission (if any)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='puzzlehunt.response'
            ),
        ),
    ]
