# Generated by Django 4.2 on 2024-09-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0014_alter_huntfile_file_alter_prepuzzlefile_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntfile',
            old_name='owner',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='prepuzzlefile',
            old_name='owner',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='puzzlefile',
            old_name='owner',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='solutionfile',
            old_name='owner',
            new_name='parent',
        ),
    ]
