# Generated by Django 4.2.20 on 2026-01-31

from django.db import migrations, models


def create_browser_platform(apps, schema_editor):
    """Create the default In-Site notification platform"""
    NotificationPlatform = apps.get_model('puzzlehunt', 'NotificationPlatform')
    NotificationPlatform.objects.get_or_create(
        type='BRWS',
        defaults={
            'name': 'In-Site Notifications',
            'enabled': True,
            'config': {}
        }
    )


def remove_browser_platform(apps, schema_editor):
    """Remove the In-Site notification platform"""
    NotificationPlatform = apps.get_model('puzzlehunt', 'NotificationPlatform')
    NotificationPlatform.objects.filter(type='BRWS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0014_submission_matched_response'),
    ]

    operations = [
        # Update the choices for NotificationPlatform.type to include BROWSER
        migrations.AlterField(
            model_name='notificationplatform',
            name='type',
            field=models.CharField(
                choices=[('DISC', 'Discord'), ('MAIL', 'Email'), ('BRWS', 'Browser')],
                help_text='The type of notification platform',
                max_length=4
            ),
        ),
        # Update the choices for Event.type to include HINT_REFUND
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(
                choices=[
                    ('PSUB', 'Submission'),
                    ('PSOL', 'Solve'),
                    ('PUNL', 'Unlock'),
                    ('HREQ', 'Hint Request'),
                    ('HRES', 'Hint Response'),
                    ('HREF', 'Hint Refund'),
                    ('FINH', 'Finish Hunt'),
                    ('TMJH', 'Team Join'),
                    ('UPDT', 'New Update')
                ],
                help_text='The type of event',
                max_length=4
            ),
        ),
        # Create the default Browser platform
        migrations.RunPython(create_browser_platform, remove_browser_platform),
    ]
