# Generated by Django 4.2.20 on 2026-01-31

from django.db import migrations


def create_subscriptions_for_existing_users(apps, schema_editor):
    """Create browser notification subscriptions for existing users."""
    User = apps.get_model('puzzlehunt', 'User')
    NotificationPlatform = apps.get_model('puzzlehunt', 'NotificationPlatform')
    NotificationSubscription = apps.get_model('puzzlehunt', 'NotificationSubscription')

    browser_platform = NotificationPlatform.objects.filter(
        type='BRWS',
        enabled=True
    ).first()

    if not browser_platform:
        return

    # Event types for browser notifications
    event_types = ','.join(['PSOL', 'PUNL', 'HRES', 'HREF'])

    for user in User.objects.all():
        # Skip if user already has a browser subscription
        if not NotificationSubscription.objects.filter(
            user=user,
            platform__type='BRWS'
        ).exists():
            NotificationSubscription.objects.create(
                user=user,
                platform=browser_platform,
                event_types=event_types,
                active=True
            )


def reverse_migration(apps, schema_editor):
    """Remove browser subscriptions."""
    NotificationSubscription = apps.get_model('puzzlehunt', 'NotificationSubscription')
    NotificationSubscription.objects.filter(platform__type='BRWS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0015_browser_notification_platform'),
    ]

    operations = [
        migrations.RunPython(create_subscriptions_for_existing_users, reverse_migration),
    ]
