# Generated by Django 4.2 on 2024-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0015_rename_owner_huntfile_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='config',
            field=models.TextField(blank=True, help_text='Configuration for puzzle, point and hint unlocking rules'),
        ),
    ]
