# Generated by Django 4.2.17 on 2025-01-01 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0017_team_num_total_hints_earned_team_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DISC', 'Discord'), ('MAIL', 'Email')], help_text='The type of notification platform', max_length=4)),
                ('name', models.CharField(help_text='A friendly name for this platform configuration', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this platform is currently enabled')),
                ('config', models.JSONField(help_text='Platform-specific configuration (API keys, URLs, etc.)')),
            ],
            options={
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_types', models.CharField(help_text='Comma-separated list of event types to notify on', max_length=255)),
                ('platform_config', models.JSONField(help_text='User-specific platform configuration (webhook URLs, channel IDs, etc.)')),
                ('active', models.BooleanField(default=True, help_text='Whether this subscription is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hunt', models.ForeignKey(blank=True, help_text='Optional: limit notifications to a specific hunt', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.hunt')),
                ('platform', models.ForeignKey(help_text='The platform to send notifications through', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.notificationplatform')),
                ('user', models.ForeignKey(help_text='The user who owns this subscription', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'hunt')},
            },
        ),
    ]
