# Generated by Django 4.2.30 on 2026-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0017_consolidate_webhook_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='display_end_date',
            field=models.DateTimeField(blank=True, help_text='The end date/time displayed to users', null=True),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='display_start_date',
            field=models.DateTimeField(blank=True, help_text='The start date/time displayed to users', null=True),
        ),
    ]
