# Generated by Django 4.2.17 on 2025-01-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0018_notificationplatform_notificationsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationplatform',
            name='config',
            field=models.JSONField(blank=True, help_text='Platform-specific configuration (API keys, URLs, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='notificationsubscription',
            name='platform_config',
            field=models.JSONField(blank=True, help_text='User-specific platform configuration (webhook URLs, channel IDs, etc.)', null=True),
        ),
    ]
