# Generated by Django 4.2.30 on 2026-07-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0018_alter_hunt_display_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDataQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The label shown to teams and on the leaderboard', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Optional help text shown under the field', max_length=255)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('BOOL', 'Yes/No'), ('SEL', 'Select (single choice)')], default='TEXT', help_text='The type of question', max_length=4)),
                ('options', models.JSONField(blank=True, default=list, help_text="Option strings; only used when question_type is 'select'")),
                ('question_order', models.IntegerField(help_text='The order in which the question is displayed')),
                ('required', models.BooleanField(default=False, help_text='Must a team answer this to register/update?')),
                ('visible_on_leaderboard', models.BooleanField(default=False, help_text='Show this as a column on the leaderboard')),
                ('used_for_grouping', models.BooleanField(default=False, help_text='Split the leaderboard by this question (only one at a time per hunt)')),
                ('hunt', models.ForeignKey(help_text='The hunt this question belongs to', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.hunt')),
            ],
            options={
                'ordering': ['question_order'],
                'unique_together': {('hunt', 'question_order')},
            },
        ),
        migrations.CreateModel(
            name='TeamDataAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text="Stored answer; boolean as 'True'/'False', select as the chosen option text", max_length=200)),
                ('question', models.ForeignKey(help_text='The question being answered', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.teamdataquestion')),
                ('team', models.ForeignKey(help_text='The team that gave this answer', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.team')),
            ],
            options={
                'verbose_name_plural': 'team data answers',
                'unique_together': {('question', 'team')},
            },
        ),
    ]
