# Generated by Django 4.2.17 on 2025-01-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0019_alter_notificationplatform_config_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationsubscription',
            unique_together=set(),
        ),
    ]
