# Generated by Django 4.2.30 on 2026-07-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0020_migrate_custom_data_to_team_data_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='custom_data',
        ),
    ]
