# Generated by Django 4.2.17 on 2025-01-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0020_alter_notificationsubscription_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsubscription',
            name='platform_config',
        ),
        migrations.AddField(
            model_name='notificationsubscription',
            name='destination',
            field=models.CharField(blank=True, help_text='Platform-specific destination (webhook URL, email, channel ID, etc.)', max_length=255, null=True),
        ),
    ]
