# Generated by Django 4.2.30 on 2026-08-04 16:47

from django.db import migrations, models


def reshape_options_to_dicts(apps, schema_editor):
    """ Convert legacy flat-string `options` (["Rookie", "Veteran"]) into the new
    {label, leaderboard_label} dict shape. Guarded on the first entry's type so this
    is safe to run more than once (e.g. after a manual re-run). """
    TeamDataQuestion = apps.get_model('puzzlehunt', 'TeamDataQuestion')
    for question in TeamDataQuestion.objects.filter(question_type='SEL').exclude(options=[]):
        if isinstance(question.options[0], str):
            question.options = [{'label': opt, 'leaderboard_label': ''} for opt in question.options]
            question.save(update_fields=['options'])


def reshape_options_to_strings(apps, schema_editor):
    """ Reverse of reshape_options_to_dicts: drops any leaderboard_label overrides. """
    TeamDataQuestion = apps.get_model('puzzlehunt', 'TeamDataQuestion')
    for question in TeamDataQuestion.objects.filter(question_type='SEL').exclude(options=[]):
        if isinstance(question.options[0], dict):
            question.options = [opt['label'] for opt in question.options]
            question.save(update_fields=['options'])


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0021_remove_team_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdataquestion',
            name='leaderboard_label',
            field=models.CharField(blank=True, help_text='Optional label for the leaderboard/participant-info columns; defaults to the question name if blank', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdataquestion',
            name='name',
            field=models.CharField(help_text='The label shown to teams when registering', max_length=100),
        ),
        migrations.AlterField(
            model_name='teamdataquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text="List of {label, leaderboard_label} objects; only used when question_type is 'select'. leaderboard_label may be blank to use label everywhere"),
        ),
        migrations.RunPython(reshape_options_to_dicts, reshape_options_to_strings),
    ]
