# Generated by Django 4.2.17 on 2025-01-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0022_alter_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text of the update announcement.', max_length=1000)),
                ('time', models.DateTimeField(help_text='The time the update was announced')),
                ('hunt', models.ForeignKey(help_text='The hunt that update is part of', on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.hunt')),
                ('puzzle', models.ForeignKey(blank=True, help_text='The puzzle this update relates to (leave blank for hunt updates)', null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzlehunt.puzzle')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PSUB', 'Submission'), ('PSOL', 'Solve'), ('PUNL', 'Unlock'), ('HREQ', 'Hint Request'), ('HRES', 'Hint Response'), ('FINH', 'Finish Hunt'), ('TMJH', 'Team Join'), ('UJTM', 'User Joined Team'), ('ULTM', 'User Left Team'), ('UPDT', 'New Update')], help_text='The type of event', max_length=4),
        ),
        migrations.DeleteModel(
            name='Errata',
        ),
    ]
