# Generated by Django 4.2.17 on 2025-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0023_update_alter_event_type_delete_errata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PSUB', 'Submission'), ('PSOL', 'Solve'), ('PUNL', 'Unlock'), ('HREQ', 'Hint Request'), ('HRES', 'Hint Response'), ('FINH', 'Finish Hunt'), ('TMJH', 'Team Join'), ('UPDT', 'New Update')], help_text='The type of event', max_length=4),
        ),
    ]
