title: PuzzleSpring
description: Documentation and guides for the PuzzleSpring project
theme: just-the-docs

# For local development and production
url: ""
baseurl: "/docs"  # Both local and production use /docs

aux_links:
  "View on GitHub":
    - "https://github.com/dlareau/puzzlespring"

# Enable search
search_enabled: true

# Default layout for documentation pages
defaults:
  - scope:
      path: ""
    values:
      layout: default 

# Callout configuration
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
  tip:
    title: Tip
    color: green 